server:
  port: 7070

logging:
  config: 'classpath:logback.xml'

gateways:
  policyGateway:
    baseurl: http://localhost:9000
  wechatGateway:
    baseurl: https://qyapi.weixin.qq.com

credentials:
  stratos:
    corpID:
    corpSecret: